name: playground

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check-secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "GITHUB_TOKEN is not set"
            exit 1
          fi
          if [ -z "$NPM_TOKEN" ]; then
            echo "NPM_TOKEN is not set"
            exit 1
          fi
          if [ -z "$SLACK_WEBHOOK" ]; then
            echo "SLACK_WEBHOOK is not set"
            exit 1
          fi
